baseURL = 'https://hsizek.github.io'
locale = 'en-us'
title = "Herbert Sizek"
copyright = "Herbert Sizek"
theme = 'ananke'
sectionPagesMenu = 'main'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$','$']]
[params]
    math=true
    site_logo = "img/HJS.svg"
    private = true
    cover_dimming_class = "bg-black-0"
    omit_header_text = true
    custom_css = ["css/custom.css"]
    featured_image = "/img/default-cover.jpg"
    mainSections = ["research","books"]

[params.ananke.social]
[params.ananke.social.networks.github]
label = "GitHub"
profile = "https://github.com/%s"
icon = "github"

[params.ananke.social.networks.linkedin]
label = "LinkedIn"
profile = "https://linkedin.com/in/%s"
icon = "linkedin"

[params.ananke.social.networks.email]
label = "Email"
profile = "mailto:%s"
icon = "envelope"

[params.ananke.social.follow]
new_window_icon = false
networks = ["email", "github", "linkedin"]

[params.ananke.social.github]
  username = "hsizek"

[params.ananke.social.linkedin]
  username = "herbert-sizek-6418a8125"

[params.ananke.social.email]
username = "sizek.herbert@gmail.com"
subject = "Contact from Website"



[caches]
  [caches.images]
    dir = ':cacheDir/images'